runner:
  image: sameersbn/gitlab-ci-multi-runner
  volumes:
    - ./data:/home/gitlab_ci_multi_runner/data
  environment:
    - CI_SERVER_URL=http://192.168.240.28/ci
    - RUNNER_TOKEN=6_Hv-vxyoGGvth7k5ZAy
    - RUNNER_DESCRIPTION=mytestrunner
    - RUNNER_EXECUTOR=shell
  restart: always

