version: "3"
services:
  gitlab:
    image: sameersbn/gitlab
    ports:
      - "2222:22"
      - "80:80"
    depends_on:
      - redis
    volumes:
      - gitlab-data:/home/git/data
    environment:
      - DEBUG=false

      - DB_ADAPTER=mysql2
      - DB_HOST=192.168.240.28
      - DB_USER=gitlab
      - DB_PASS=password
      - DB_NAME=gitlabhq_production

      - REDIS_HOST=redis
      - REDIS_PORT=6379

      - GITLAB_HOST=192.168.240.28
      - GITLAB_PORT=80
      - GITLAB_SSH_PORT=2222
      - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alpha-numeric-string
      - GITLAB_SECRETS_SECRET_KEY_BASE=long-and-random-alphanumeric-string
      - GITLAB_SECRETS_OTP_KEY_BASE=long-and-random-alphanumeric-string

      - SMTP_HOST=smtp.emoney.cn
      - SMTP_USER=baoyifeng@emoney.cn
      - SMTP_PASS=baoyifeng@emoney.cn
      - SMTP_DOMAIN=emoney.cn

    restart: always

  redis:
    image: sameersbn/redis
    restart: always

volumes:
  gitlab-data:
