wekan:
  image: wekanteam/wekan
  restart: always
  links:
    - wekandb
  environment:
    - MONGO_URL=mongodb://wekandb/wekan
    - ROOT_URL=http://192.168.8.211:8081/
  ports:
    - 8081:80

wekandb:
   image: mongo
   restart: always
   volumes:
     - /home/wekan/data:/data/db